"""
Slack publishing.

  build_blocks(report)        -> Block Kit payload (the text newsletter)
  SlackPublisher.publish(...) -> posts the message, then uploads charts as
                                 threaded replies via the *current* upload flow.

IMPORTANT (verified against Slack docs): the legacy `files.upload` was sunset
on 2025-11-12. We use slack_sdk's `files_upload_v2`, which wraps
`files.getUploadURLExternal` + `files.completeUploadExternal`. Required bot
scopes: `chat:write`, `files:write`.
"""

from __future__ import annotations

import datetime as dt

import requests

from .analytics import TYPE_LABELS

SEV_EMOJI = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵"}


def _fmt_date(ts: int) -> str:
    return dt.datetime.utcfromtimestamp(ts).strftime("%b %d, %Y")


def _trend_arrow(delta: int) -> str:
    return "🔺" if delta > 0 else "🔻" if delta < 0 else "▪️"


def build_blocks(report: dict, workspace: str = "") -> list[dict]:
    ov = report["overall"]
    start = _fmt_date(report["window_start"])
    end = _fmt_date(report["generated_at"])
    total_overdue = sum(p["overdue_open"] for p in report["products"].values())
    net = ov["opened_this_period"] - ov["closed_this_period"]
    net_txt = f"{'+' if net > 0 else ''}{net}"

    blocks: list[dict] = [
        {"type": "header", "text": {"type": "plain_text",
         "text": "🛡️  Product Security Newsletter", "emoji": True}},
        {"type": "context", "elements": [{"type": "mrkdwn",
         "text": (f"*{start} – {end}*  ·  {len(report['products'])} products"
                  + (f"  ·  {workspace}" if workspace else "")
                  + "  ·  data via Aikido")}]},
        {"type": "divider"},
        # Executive summary
        {"type": "section", "fields": [
            {"type": "mrkdwn", "text": f"*Open issues*\n{ov['open']}"},
            {"type": "mrkdwn", "text": f"*Critical / High*\n"
             f"{ov['severity_open']['critical']} 🔴  /  {ov['severity_open']['high']} 🟠"},
            {"type": "mrkdwn", "text": f"*Past SLA*\n{total_overdue} overdue"},
            {"type": "mrkdwn", "text": f"*Median MTTR*\n"
             f"{ov['mttr_all']['median'] if ov['mttr_all']['median'] is not None else '—'} days"},
            {"type": "mrkdwn", "text": f"*Opened / Closed (period)*\n"
             f"{ov['opened_this_period']} / {ov['closed_this_period']}"},
            {"type": "mrkdwn", "text": f"*Net backlog Δ*\n{net_txt}"},
        ]},
    ]

    # Insights
    if report["insights"]:
        bullets = "\n".join(f"•  {s}" for s in report["insights"])
        blocks += [{"type": "section",
                    "text": {"type": "mrkdwn", "text": f"*📌 Insights*\n{bullets}"}}]

    # Leaderboard (monospace table)
    blocks.append({"type": "divider"})
    rows = ["```", f"{'Product':<16}{'Risk':>6}{'Crit':>6}{'High':>6}{'Overdue':>9}{'MTTR':>7}  Δcrit"]
    for b in report["leaderboard"]:
        mttr = f"{b['mttr_median']:g}d" if b["mttr_median"] is not None else "—"
        rows.append(
            f"{b['name'][:15]:<16}{b['risk_score']:>6}{b['open_critical']:>6}"
            f"{b['open_high']:>6}{b['overdue']:>9}{mttr:>7}  {_trend_arrow(b['crit_delta'])}"
        )
    rows.append("```")
    blocks.append({"type": "section", "text": {"type": "mrkdwn",
                   "text": "*🏆 Product risk leaderboard*\n" + "\n".join(rows)}})

    # Most critical open issues
    if report["top_critical_issues"]:
        blocks.append({"type": "divider"})
        lines = []
        for c in report["top_critical_issues"][:6]:
            tag = TYPE_LABELS.get(c["type"], c["type"])
            ident = c["cve"] or c["package"] or tag
            overdue = "  ⏰ *overdue*" if c["overdue"] else ""
            lines.append(
                f"{SEV_EMOJI.get(c['severity'], '⚪')} *{c['rule']}* "
                f"(`{c['severity']}` {c['score']})\n"
                f"      {c['product']} · {c['repo'] or '—'} · {ident} · "
                f"{c['age_days']}d old{overdue}"
            )
        blocks.append({"type": "section", "text": {"type": "mrkdwn",
                       "text": "*🔥 Most critical open findings*\n" + "\n".join(lines)}})

    # Top weakness classes
    if report["top_cwes"]:
        cwe_txt = "   ".join(f"`{c}` ×{n}" for c, n in report["top_cwes"][:6])
        blocks.append({"type": "context", "elements": [
            {"type": "mrkdwn", "text": f"*Top CWE classes:*  {cwe_txt}"}]})

    blocks.append({"type": "context", "elements": [{"type": "mrkdwn",
                   "text": "Charts in thread :thread:  ·  "
                           "_Generated by aikido-product-newsletter_"}]})
    return blocks


def image_blocks(charts: dict[str, str], base_url: str) -> list[dict]:
    """Block Kit image blocks referencing publicly-hosted chart PNGs.

    Used for the webhook path, which cannot upload files — Slack only renders
    images from a reachable `image_url`. `base_url` is where you host the PNGs
    (e.g. an S3/GCS bucket or GitHub Pages); filenames match charts.render_all.
    """
    base = base_url.rstrip("/")
    order = ["risk_leaderboard", "severity_by_product", "opened_vs_closed_trend",
             "mttr_by_severity", "issue_type_mix", "open_aging", "top_cwes"]
    blocks: list[dict] = [{"type": "divider"}]
    for name in order:
        if name in charts:
            blocks.append({
                "type": "image",
                "alt_text": name.replace("_", " "),
                "title": {"type": "plain_text",
                          "text": name.replace("_", " ").title()},
                "image_url": f"{base}/{name}.png",
            })
    return blocks


class SlackWebhookPublisher:
    """Simplest path: POST the Block Kit message to an incoming-webhook URL.

    No bot token, scopes, or channel needed — the webhook is bound to a channel
    at creation and the URL is the only credential. Charts can only be shown if
    you pass `chart_base_url` pointing at publicly-hosted PNGs (webhooks can't
    upload files); otherwise the text newsletter is posted on its own.
    """

    def __init__(self, webhook_url: str, chart_base_url: str | None = None):
        self._url = webhook_url
        self._chart_base_url = chart_base_url

    def publish(self, blocks: list[dict], charts: dict[str, str] | None = None,
                text_fallback: str = "Product Security Newsletter") -> None:
        payload_blocks = list(blocks)
        if self._chart_base_url and charts:
            payload_blocks += image_blocks(charts, self._chart_base_url)
        resp = requests.post(
            self._url,
            json={"blocks": payload_blocks, "text": text_fallback},
            timeout=30,
        )
        # Incoming webhooks return 200 + body "ok" on success.
        if resp.status_code != 200 or resp.text.strip() not in ("ok", ""):
            raise RuntimeError(
                f"Slack webhook failed ({resp.status_code}): {resp.text[:300]}")


class SlackBotPublisher:
    """Bot-token path: posts the message, then uploads charts in-thread via the
    current `files_upload_v2` flow. Needs scopes chat:write + files:write and
    the bot invited to the channel — but no public image hosting."""

    def __init__(self, bot_token: str):
        try:
            from slack_sdk import WebClient
        except ImportError as e:  # pragma: no cover
            raise RuntimeError("pip install slack_sdk") from e
        self._client = WebClient(token=bot_token)

    def publish(self, channel: str, blocks: list[dict], charts: dict[str, str],
                text_fallback: str = "Product Security Newsletter") -> str:
        msg = self._client.chat_postMessage(
            channel=channel, blocks=blocks, text=text_fallback, unfurl_links=False)
        ts = msg["ts"]
        for name, path in charts.items():
            self._client.files_upload_v2(
                channel=channel, thread_ts=ts, file=path,
                title=name.replace("_", " ").title(),
            )
        return ts


# Backwards-compatible alias
SlackPublisher = SlackBotPublisher
